### ISSUE TITLE
TFtools fails when using a for_each in a resource block

### ISSUE THREAD

**Issue by leahecole** [GoogleCloudPlatform/terraform-sample-tools#10]
I'm trying to convert a terraform file right now while following the README and it creates the same resources for multiple projects and the name is determined from the [value from the each object](https://www.terraform.io/language/meta-arguments/for_each#the-each-object) - this causes tftools to fail

**Comment by leahecole** [comment]
cc @msampathkumar - I see you're a big contributor on here - maybe you can help me triage this issue? 😄

**Comment by leahecole** [comment]
To replicate, take the terraform file in this PR and run it with two projects that have Composer environments. If you need access to two projects to test this on, let me know https://github.com/leahecole/composer_monitoring/tree/main/Cross_Project_Composer_Monitoring

**Comment by leahecole** [comment]
This is covered in the README, but these will be the lines you modify https://github.com/leahecole/composer_monitoring/blob/89ddfb18ef1ad2304e444488d6eb53a248ce3299/Cross_Project_Composer_Monitoring/main.tf#L23-L25

You must have one project that acts as your main project and then at minimum one in the list of monitored projects

**Comment by msampathkumar** [comment]
Hi @leahecole Thank you for the ticket. I will check into this soon.
