### ISSUE TITLE
Parsing error when name includes . character

### ISSUE THREAD

**Issue by rogerthatdev** [GoogleCloudPlatform/terraform-sample-tools#11]
The resource [cloud_run_domain_mapping](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_domain_mapping#name) has a name attribute that must be a verified domain. Running tftools on a cloud_run_domain_mapping resource with `name = "verified-domain.com"`, for example, yields a parsing error from `convert2erb.py` due to the dot.  

[cloud_run_domain_mapping.tf.txt](https://github.com/GoogleCloudPlatform/terraform-sample-tools/files/9106587/cloud_run_domain_mapping.tf.txt)

**Comment by msampathkumar** [comment]
Hi @rogerthatdev Thank you for the detailed bug report. Thanks to you, I made necessary changes for resolving this issue in our updated version.

Note: update version needs install of `ANTLR4`

Can you please check?

**Comment by msampathkumar** [comment]
Request you to re-open this issue, if needed be! Thanks.
