### ISSUE TITLE
tftools reorders attributes

### ISSUE THREAD

**Issue by betsy-lichtenberg** [GoogleCloudPlatform/terraform-sample-tools#12]
My TF file had "name" as the first attribute in each resource.
After running tftools, the resulting .erb file no longer has "name" as the first attribute in each resource.

For testing, you can use https://paste.googleplex.com/4746285415399424.

**Comment by msampathkumar** [comment]
Hi @betsy-lichtenberg, 

For the code sample you have shared, can you please also share the expected .erb & .yaml file please?

In the latest branch, we have an automated `tests`, just adding files(source & expected files) at `tests/samples/basic_testXX/convert2tf/` When I tested the provided code, it is working fine.

**Comment by betsy-lichtenberg** [comment]
I just retested, and it's working fine now. Thanks!
