### ISSUE TITLE
Minor Issues - Tftools

### ISSUE THREAD

**Issue by msampathkumar** [GoogleCloudPlatform/terraform-sample-tools#4]
For `tftools`, the help link provided is outdated. Following is the url provided by it.

https://github.com/msampathkumar/MagicModules-TerraformTools/tree

Please check and update.

**Comment by naksh-atra** [comment]
hello, i am learning how to contribute, what should i do in this? what i can see is a misplaced 't' at the beginning of the link, the link itself doesn't work but the magicmodules repo exists and so does terraformtools.

**Comment by msampathkumar** [comment]
@naksh-atra Sorry for delay. Thank your for your interest. You can do these (1) fork the this repo (2) commit your changes (3) submit a Pull request to this Repository.

After a PR is submitted, I/other repo admins can check and accept/reject/suggest further updates depending of the circumstance.

**Comment by msampathkumar** [comment]
@naksh-atra If you are referreing to `\thttp://...` please note that prefix t is actually `\t` which refer to `tab space`
