### ISSUE TITLE
tftools replaces wrong primary resource

### ISSUE THREAD

**Issue by cbonnie** [GoogleCloudPlatform/terraform-sample-tools#8]
In the snippet below, I selected `google_pubsub_topic` as the primary resource when I ran tftools. However, the output for tftools replaced the line `resource "google_pubsub_topic_iam_binding" "binding" {` with `resource "google_pubsub_topic" "<%= ctx[:primary_resource_id] %>" {`. 

main.tf

```
# [START storage_create_pubsub_notifications_tf]
resource "google_storage_notification" "notification" {
  bucket         = google_storage_bucket.bucket.name
  payload_format = "JSON_API_V1"
  topic          = google_pubsub_topic.topic.id
  depends_on = [google_pubsub_topic_iam_binding.binding]
}

// Enable notifications by giving the correct IAM permission to the unique service account.
data "google_storage_project_service_account" "gcs_account" {
}

resource "google_pubsub_topic_iam_binding" "binding" {
  # name    = "default_iam_binding"
  topic   = google_pubsub_topic.topic.id
  role    = "roles/pubsub.publisher"
  members = ["serviceAccount:${data.google_storage_project_service_account.gcs_account.email_address}"]
}

// End enabling notifications
resource "google_storage_bucket" "bucket" {
  name     = "example-bucket-name"
  location = "US"
  uniform_bucket_level_access = true
}

resource "google_pubsub_topic" "topic" {
  name = "your_topic_name"
}
# [END storage_create_pubsub_notifications_tf]
```

Additionally, when I ran tftools on this snippet, it only gave me the option to pick between two primary resources: `google_pubsub_topic` and `google_storage_bucket`. I expected to also be able to select `google_storage_notification` or `google_pubsub_topic_iam_binding`.

**Comment by cbonnie** [comment]
I ran into this issue as I was working on https://github.com/GoogleCloudPlatform/magic-modules/pull/6031

**Comment by msampathkumar** [comment]
Hi @cbonnie Thank you for the bug report. This is one of edge case issue we are planning to fix in the next version(Currently, we are using regex rules).

`tftools` expects a `name` row just after `resource` definition for some confirmation checks. As immediate hack, you can add `name` row temporarily and remove them in the output. Hope this solves your issue for a some extent.

**Comment by msampathkumar** [comment]
Hi @cbonnie Thank you for the report. To fix this kind of issues, wrote a new Terraform HCL language Parser

Can you please try using our latest branch `tftools-dev-feature-antlr4-parser`? 

I have added a test case @ https://github.com/GoogleCloudPlatform/terraform-sample-tools/tree/tftools-dev-feature-antlr4-parser/tools/magic-modules-tftools/tests/samples/basic_test05 based on the provided code snippet. So far everything looks good.

If you are familiar with dockers, I added docker images as well. Please check this dev branch's readme.me

**Comment by msampathkumar** [comment]
Request you to re-open this issue, if needed be! Thanks.
