### ISSUE TITLE
No module named 'termcolor'

### ISSUE THREAD

**Issue by ace-n** [GoogleCloudPlatform/terraform-sample-tools#9]
## Problem
When I try to run `tftools` on OSX (Monterey - 12.4), I get this error:

> No module named `termcolor`

This is despite **a)** explicitly installing it (in my current `venv`, with `pip`) and **b)** trying to run `setup.py`.

## Attempted fix 1
When I run `sudo python3 setup.py install`, I get the following error:
```
error: Setup script exited with error: SandboxViolation: mkdir('/private/var/root/Library/Caches/com.apple.python/private', 511) {}

The package setup script has attempted to modify files on your system
that are not within the EasyInstall build area, and has been aborted.

This package cannot be safely installed by EasyInstall, and may not
support alternate installation locations even if you run its setup
script by hand.  Please inform the package's author and the EasyInstall
maintainers to find out if a fix or workaround is available.
```

I can work around this by adding a `sys.dont_set_bytecode = True` to `setup.py` as documented [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1679370#c8), but that does **not** resolve the missing `termcolor` package.

## Attempted fix 2
Copying the Python package over manually:
```
sudo cp -r /usr/local/Cellar/pyenv/2.3.1/versions/3.8.13/envs/python-docs-samples/lib/python3.8/site-packages/termcolor-1.1.0-py3.8.egg-info /Library/Python/3.8/site-packages/
```

(This didn't work either.)

## Suggested fix
It seems like `easy_install` is [no longer preferred](https://stackoverflow.com/questions/3220404/why-use-pip-over-easy-install) within the Python community. One of two things is possible:
1) My Mac's Python installation is misconfigured (and _should_ be using something else, not `easy_install`)
2) We should move this repo to a `pip`-based system with `requirements.txt`.

**Comment by msampathkumar** [comment]
Hi, @ace-n Thank you for suggestions. Like you suggested, we will move to pip soon.

Recently, while working with a colleague we have found that in their Mac system, has two python versions installed along with two pip tools (python, python3, pip, pip3 all are present). Using virtual environment will localise this issue and give multiple benefits to users.

can you try using a virtual environment https://docs.python.org/3/tutorial/venv.html and suggest if you still face issue ?

**Comment by ace-n** [comment]
@msampathkumar I'm comfortable closing this issue (without explicit testing) once y'all move to `pip`.

(If that _doesn't_ fix it, I can reopen the issue if need be. :+1: )

**Comment by msampathkumar** [comment]
Hi @ace-n. Thanks to you, this issue is now fixed.

On a different note, I am working a new version for this tftools. Docker support is included. I can work on creating a pip, but it might take some time as I need to re-asses, few dependencies. Newer version is very high accuracy at parsing and less prone to error too but need jre & Antlr4 setup.
